### ISSUE TITLE
[BUG] - definities in dl komen op 1 lijn te staan

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-search-results#18]
**Omschrijf het probleem**
De content slot van de vl-search-result is een dl. Een dl kan meerdere dt/dd combinaties bevatten. Maar als een dd (de waarde) leeg is, dan komen de 2 dts (de labels) op 1 lijn te staan

**Hoe te reproduceren**
Voorbeeld zoals op de demo pagina:
```
  <vl-search-result>
    <a href="#" slot="title">Titel</a>
    <dl slot="content">
      <dt>Label A</dt>
      <dd></dd>
      <dt>Label B</dt>
      <dd>waarde b</dd>
    </dl>
  </vl-search-result>
```

Geeft het volgende: 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/58428396/106296384-e3e15300-6251-11eb-9229-e4c1edd09bbf.png">

**Gewenst gedrag**
dt tags komen niet op 1 lijn te staan als een dd leeg is.

**extra info**
Er is een workaround om de bug te vermijden: meerdere content slots:

```
  <vl-search-result>
    <a href="#" slot="title">Titel</a>
    <dl slot="content">
      <dt>Label A</dt>
      <dd></dd>
    </dl>
    <dl slot="content">
      <dt>Label B</dt>
      <dd>waarde b</dd>
    </dl>
  </vl-search-result>
```

**Comment by coemans** [comment]
Native geven volgende code voorbeelden hetzelfde visueel resultaat:

``` HTML
<dl>
  <dt>Type 1</dt>
  <dd></dd>
  <dt>Type 2</dt>
  <dd>Type 2 definition</dd>
</dl>
```
``` HTML
<dl>
  <dt>Type 1</dt>
  <dt>Type 2</dt>
  <dd>Type 1-2 definition</dd>
</dl>
```

Dus een lege `<dd/>` lijkt standaard voor verwarring te zorgen. We zouden kunnen kijken naar een oplossing maar het lijkt me beter om altijd een waarde te tonen, ook al is er geen waarde. Er zou dan tekstueel vermeld kunnen worden dat er geen waarde is. Voor de eindgebruiker is dit dan ook helder. Te bevestigen maar in kader van WCAG lijkt me dit ook beter dan een lege tag.

**Comment by Veyfeyken** [comment]
Het is een visueel probleem dat dus best ook via CSS wordt opgelost? 

De workaround voegt een tweede description list toe terwijl het semantisch gezien maar om 1 lijst gaat. Dan voldoet de inhoud niet aan het WCAG criterium 1.3.1 Info and Relationships. Screenreaders zullen 2 dl's aankondigen terwijl het visueel maar om 1 gaat.

**Comment by coemans** [comment]
Het zou inderdaad via CSS opgelost moeten worden, maar aangezien het native visueel identiek is lijkt me dat niet nodig. De workaround raad ik inderdaad zeker niet aan en is bij de nieuwste versie niet meer nodig (slots) daar de structuur in kader van WCAG gewijzigd werd naar:

```HTML
<ul is="vl-search-results">
    <li is="vl-search-result">
        <a href="#">Vlaanderenkiest.be</a>
        <time>Maandag 22 oktober 2018</time>
        <dl>
            <dt>Vlaanderenkiest.be</dt>
            <dd>Verkiezingsresultaten op Vlaanderenkiest.be...</dd>
            <dt>Vlaanderen intern</dt>
            <dd>Werkt u bij de Vlaamse overheid...</dd>
        </dl>
    </li>
</ul>
```

@Veyfeyken is er een verschil op WCAG niveau of van interpretatie van screen readers tussen mijn 2 voorbeelden?

**Comment by Veyfeyken** [comment]
Er is helaas slechte ondersteuning voor `<dl>` onder screenreaders waardoor ik die vraag niet goed kan beantwoorden. Best wel vreemd dat er geen goede support is voor zo'n oud HTML element. Meer info: https://a11ysupport.io/tech/html/dl_element

> The dl element and its associated dt and dd elements have poor to non-existent support. If it is critically important to convey relationships between terms and descriptions and the values of the two can be confused with each other (think a matching list of colors such as "red: blue", consider another approach such as a table or headings. It is often possible for a user to determine which text is a key and which text is a value just based upon the text alone. If this is the case for your implementation, it might be fine to use a dl element and hope for better support in the future.

In mijn test met VoiceOver op macOS is er wel een subtiel verschil tussen de twee. Met NVDA op Windows niet.

De 2 voorbeelden zijn native misschien wel visueel identiek maar semantisch is er toch een verschil. Je mag multiple terms definiëren die gekoppeld zijn aan 1 description en andersom:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

Daardoor geeft een lege `<dd>` een andere betekenis aan de lijst dan wanneer je een `<dd>` weglaat.

**Comment by Veyfeyken** [comment]
```html
<ul is="vl-search-results">
    <li is="vl-search-result">
        <a href="#">Vlaanderenkiest.be</a>
        <time>Maandag 22 oktober 2018</time>
        <dl>
            <dt>Vlaanderenkiest.be</dt>
            <dd>Verkiezingsresultaten op Vlaanderenkiest.be...</dd>
            <dt>Vlaanderen intern</dt>
            <dd>Werkt u bij de Vlaamse overheid...</dd>
        </dl>
    </li>
</ul>

```

@coemans Dit is valide HTML maar niet de meest toegankelijke manier om een lijst van zoekresultaten weer te geven lijkt me. Een lijst is prima maar daar nog een `<dl>`in nesten maakt het onnodig complex en semantisch gezien lijken me zoekresultaten ook geen definitielijst.

**Comment by coemans** [comment]
> @coemans Dit is valide HTML maar niet de meest toegankelijke manier om een lijst van zoekresultaten weer te geven lijkt me. Een lijst is prima maar daar nog een <dl>in nesten maakt het onnodig complex en semantisch gezien lijken me zoekresultaten ook geen definitielijst.

@Veyfeyken dat staat inderdaad nog genoteerd op het intern WCAG ticket en zal daar verder bekeken worden.

Ik zal ticket behouden om op CSS niveau iets te voorzien indien afnemers er alsnog voor kiezen liever geen waarde in te vullen dan een betekenisvolle waarde.
